config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/new'
  get 'pages/search', to: 'pages#search', as: 'search'
  
  post 'characters' => 'pages#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/character.rb
class Character < ApplicationRecord
    validates :name, presence: true 
    validates :location, presence: true
    validates :house, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def search
    @search_results = []

    if params[:query].present? && params[:field].present?
      case params[:field]
      when 'name'
        @search_results = Character.where("name LIKE ?", "%#{params[:query]}%")
      when 'location'
        @search_results = Character.where("location LIKE ?", "%#{params[:query]}%")
      when 'house'
        @search_results = Character.where("house LIKE ?", "%#{params[:query]}%")
      end
    end
  end

  def new
    @character = Character.new
  end
  
  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to pages_index_path
    else
      render :new
    end
  end

  private

  def character_params
    params.require(:character).permit(:name, :location, :house)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioHowratsRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-info bg-gradient">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Lista", pages_index_path, class: "nav-link" %>
            <%= link_to "Nuevo", pages_new_path, class: "nav-link" %>
            <%= link_to "Buscar", search_path, class: "nav-link" %>
          </div>
        </div>
      </div>
    </nav>
    
    <div class="container">
      <h1 class="my-5">Harry Potter App</h1>
      <%= yield %>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/index.html.erb
<div class="row">
    <% Character.all.each do |e| %>
        <div class="col-4 mb-3">
            <ul class="list-group">
                <li class="list-group-item"><strong>Nombre: </strong><%= e.name %></li>
                <li class="list-group-item"><strong>Localizacion: </strong><%= e.location %></li>
                <li class="list-group-item"><strong>Casa: </strong><%= e.house %></li>
            </ul>
        </div>
    <% end %>
</div>

app/views/pages/new.html.erb
<div class="row">
    <div class="col-4">
        <h2>Nueva Entrada</h2>
        <%= form_with model: @character, method: :post do |form| %>
            <div class="mb-3">
                <%= form.label :name, "Nombre ", class: "form-label"%>
                <%= form.text_field :name, required: true, class: "form-control"%>
            </div>
            <div class="mb-3">
                <%= form.label :location, "Localizacion ", class: "form-label"%>
                <%= form.text_field :location, required: true, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= form.label :house, "Casa ", class: "form-label"%>
                <%= form.text_field :house, required: true, class: "form-control" %>
            </div>
            <%= form.submit "Submit", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/pages/search.html.erb
<div class="row">
    <div class="col-4">
        <h2>Elige que quieres buscar</h2>
        <% entrada = params[:query] %>
        <%= form_with url: search_path, method: 'get' do |form| %>
          <%= form.text_field :query, value: entrada, class: "form-control" %>
          <%= form.select :field, options_for_select([['Nombre', 'name'], ['Localizacion', 'location'], ['Casa', 'house']], params[:field]), prompt: 'Selecciona un campo', class: "form-select" %>
          <%= form.submit "Buscar", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>
<div class="row">
    <% if entrada.present? %>
      <% @search_results.each do |e| %>
          <div class="col-4 mb-3">
              <ul class="list-group">
                  <li class="list-group-item"><strong>Nombre: </strong><%= e.name %></li>
                  <li class="list-group-item"><strong>Localizacion: </strong><%= e.location %></li>
                  <li class="list-group-item"><strong>Casa: </strong><%= e.house %></li>
              </ul>
          </div>
      <% end %>
    <% end %>
</div>

<br>

<br>